/* Motor independiente: criterios de la copia de RM 375-2008-TR suministrada. */
(function(root){
  'use strict';
  function num(v,min=0,max=Infinity){if(v===''||v===null||v===undefined||!Number.isFinite(Number(v)))throw Error('Completa todos los valores numéricos.');v=Number(v);if(v<min||v>max)throw Error(`Valor fuera de rango: se requiere entre ${min} y ${max}.`);return v;}
  const thermal={si:{100:[29.5,27.5,26,null],75:[30.5,28.5,27.5,null],50:[31.5,29.5,28.5,27.5],25:[32.5,31,30,29.5]},no:{100:[27.5,25,22.5,null],75:[29,26.5,24.5,null],50:[30,28,26.5,25],25:[31,29,28,26.5]}};
  function ruido(rows){if(!rows.length)throw Error('Añade al menos un tramo.');let dose=0,time=0,energy=0;const detail=rows.map(([l,h])=>{l=num(l,0,150);h=num(h,.001,24);const t=8/2**((l-85)/3);dose+=h/t;time+=h;energy+=h*10**(l/10);return {l,h,t,percent:100*h/t};});if(time>24)throw Error('La exposición acumulada no puede superar 24 horas.');return {dose:100*dose,time,leq:10*Math.log10(energy/time),detail,exceeds:dose>1+1e-10};}
  function wbgt(solar,tbh,tg,tbs,aclim,regimen,load){tbh=num(tbh,-20,65);tg=num(tg,-20,100);if(solar)tbs=num(tbs,-20,65);const index=['leve','moderada','pesada','muy'].indexOf(load);if(index<0||!thermal[aclim]?.[regimen])throw Error('Selecciona condiciones válidas.');const value=.7*tbh+(solar?.2*tg+.1*tbs:.3*tg),limit=thermal[aclim][regimen][index];return {value,limit,exceeds:limit===null?null:value>limit+1e-10};}
  function luz(value,limit){value=num(value,0,200000);limit=num(limit,1);return {value,limit,deficit:Math.max(0,limit-value),exceeds:value<limit};}
  function traccion(value,unit,person,phase){value=num(value,0,100000);if(!['hombre','mujer'].includes(person)||!['inicio','marcha'].includes(phase))throw Error('Selecciona persona y fase.');const kgf=unit==='N'?value/9.80665:value;const limit=phase==='inicio'?(person==='hombre'?25:15):(person==='hombre'?10:7);return {kgf,limit,newtons:kgf*9.80665,exceeds:kgf>limit+1e-10};}
  function humedad(v){v=num(v,0,100);return {value:v,status:v<40?'Por debajo de 40 %':v>90?'Por encima de 90 %':'Dentro de 40–90 %',exceeds:v<40||v>90};}
  function vibracion(v,h,mode){v=num(v,0,100);h=num(h,.001,24);if(mode==='cuerpo'){if(h!==8)return {value:v,limit:null,status:'La tabla del numeral 33 solo permite comparar una exposición de 8 h.'};return {value:v,limit:1.15,status:v>1.15?'Supera el límite':v>=.5?'Alcanza el nivel de acción':'Por debajo del nivel de acción',exceeds:v>1.15,action:v>=.5};}if(h>8)return {value:v,limit:null,status:'No hay banda tabulada para más de 8 h.'};const limit=h>=4?4:h>=2?6:h>=1?8:12;return {value:v,limit,exceeds:v>limit,status:v>limit?'Supera la banda':'No supera la banda'};}
  function niosh(lc,factors){lc=num(lc,.001,100);if(factors.length!==6)throw Error('Se requieren los seis factores.');const checked=factors.map(v=>num(v,0,1));return {value:checked.reduce((a,b)=>a*b,lc),zero:checked.includes(0)};}
  const api={num,thermal,ruido,wbgt,luz,traccion,humedad,vibracion,niosh};if(typeof module!=='undefined')module.exports=api;root.Ergo=api;
})(typeof globalThis!=='undefined'?globalThis:this);
