'use strict';
// Extiende la interfaz original; las funciones revisadas sustituyen sus cálculos.
const E=globalThis.Ergo;
const val=id=>document.getElementById(id).value;
const number=id=>E.num(val(id));
const fmt=(v,d=1)=>v.toLocaleString('es-PE',{minimumFractionDigits:d,maximumFractionDigits:d});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const result=(id,fn)=>{try{$(id).innerHTML=fn()}catch(e){$(id).innerHTML=box('warn','Revisa los datos','',esc(e.message),'No se ha emitido una clasificación.')}};
const field=(id,label,value,extra='')=>`<label>${label}<input id="${id}" type="number" value="${value}" step="any" ${extra}></label>`;
const select=(id,label,options)=>`<label>${label}<select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
document.querySelector('header').insertAdjacentHTML('beforeend','<div class="credit">Desarrollado por Sergio Bravo con Astra · Edición docente</div>');
document.querySelector('.notice').innerHTML='<strong>Observa → calcula → argumenta → mejora.</strong> Basado en la copia suministrada de la RM 375-2008-TR. Las categorías se refieren únicamente al criterio seleccionado, no certifican la seguridad integral del puesto. No se evalúa aquí la vigencia de otras disposiciones ni se sustituyen mediciones profesionales.';
function openPanel(id){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.setAttribute('aria-selected',String(x.dataset.target===id)));}
function addPanel(id,label,content){const b=document.createElement('button');b.className='tab';b.dataset.target=id;b.setAttribute('aria-selected','false');b.textContent=label;b.onclick=()=>openPanel(id);document.querySelector('.tabs').appendChild(b);const s=document.createElement('section');s.id=id;s.className='panel';s.innerHTML=content;document.querySelector('.footer-tools').before(s);}

// Resultados obsoletos se invalidan al editar un dato.
document.addEventListener('input',event=>{const panel=event.target.closest('.panel');if(panel)panel.querySelectorAll('.result').forEach(x=>{x.textContent='Datos modificados. Vuelve a calcular para actualizar el resultado.'})});
window.limpiar=()=>{$('resCarga').textContent='Resultado borrado. Los datos se mantienen.'};
window.calcCarga=()=>result('resCarga',()=>{const person=val('persona');if(person==='gestante')return box('bad','No se permite manipulación manual','', 'El numeral 12 prohíbe la manipulación manual de cargas durante el embarazo. No se interpreta como un límite de 0 kg.','Numeral 12.');const w=E.num(val('peso'),.001,1000),f=E.num(val('frecuencia'),0,10000),h=E.num(val('horasCarga'),.001,24),male=person==='hombre',prot=val('proteccion');const limit=prot==='general'?(male?25:15):prot==='mayor'?(male?15:9):(male?40:24);const reasons=[];if(w>limit)reasons.push('El peso supera el valor de la tabla seleccionada.');if(w>(male?25:15))reasons.push('El numeral 6 indica favorecer ayudas mecánicas apropiadas.');if($('voluminosa').checked)reasons.push('Reducir tamaño y volumen: ambas dimensiones superan 60 cm.');if($('desnivel').checked)reasons.push('Evitar manejo de cargas en cuestas, escalones o escaleras.');const sig=h>2&&((w>=40&&f*h>=1)||(w>=25&&f>12)||(w>=5&&f>120)||(w<3&&f>240));if(sig)reasons.push('Tamizaje: peso/frecuencia y duración indican evaluación detallada (n. 38).');return box(reasons.length?'bad':'ok',reasons.length?'Requiere revisión o intervención':'No supera la tabla seleccionada',`${fmt(w)} / ${limit} kg`,reasons.join('<br>')+'<br><br>La tabla no sustituye NIOSH ni la valoración de postura, agarre, distancia y frecuencia. Los valores de 40/24 kg son excepcionales; no son una autorización general.','Numerales 4–6, 9–12 y 38.');});
window.calcRuido=()=>result('resRuido',()=>{const r=E.ruido([...document.querySelectorAll('.noise-row')].map(row=>[row.querySelector('.db').value,row.querySelector('.nh').value]));const attention=$('altaAtencion').checked&&r.leq>=65;return box(r.exceeds||attention?'bad':'ok',r.exceeds?'Dosis superior al criterio':attention?'Revisar criterio de alta atención':'No supera los criterios seleccionados',`${fmt(r.dose)} %`,`Dosis = Σ(C/T) × 100. Exposición registrada: ${fmt(r.time)} h.<br>LAeq del período registrado: <strong>${fmt(r.leq)} dB</strong>. ${$('altaAtencion').checked?'Comparación de alta atención: debe ser <65 dB.':'Alta atención no seleccionada.'}<br><br><table><thead><tr><th>dB</th><th>C (h)</th><th>T (h)</th><th>Dosis %</th></tr></thead><tbody>${r.detail.map(x=>`<tr><td>${fmt(x.l)}</td><td>${fmt(x.h)}</td><td>${fmt(x.t,2)}</td><td>${fmt(x.percent)}</td></tr>`).join('')}</tbody></table><p>LAeq = 10 log10[Σ(C × 10^(L/10))/ΣC]. Solo representa los tramos ingresados; no extrapola períodos omitidos.</p>`,'Numerales 23–25. Se utiliza la ecuación del n. 24; puede diferir del redondeo de la tabla del n. 23.');});
window.calcWBGT=()=>result('resWBGT',()=>{const r=E.wbgt(val('solar')==='si',val('tbh'),val('tg'),val('tbs'),val('aclim'),val('regimen'),val('cargaTerm'));return box(r.limit===null?'warn':r.exceeds?'bad':'ok',r.limit===null?'Sin valor tabulado':r.exceeds?'Supera el límite':'No supera el límite',`${fmt(r.value)} °C`,r.limit===null?'No se interpreta una casilla vacía como segura. Requiere evaluación especializada.':`Límite: ${fmt(r.limit)} °C. Diferencia: ${fmt(r.value-r.limit)} °C.<br>Fórmula: ${val('solar')==='si'?'0,7 Tbh + 0,2 Tg + 0,1 Tbs':'0,7 Tbh + 0,3 Tg'}.<br>Clasificación con el valor sin redondear. Verifica aclimatación, carga metabólica, ropa y mediciones apropiadas.`,'Numerales 26–27.');});
window.calcLuz=()=>result('resLuz',()=>{const r=E.luz(val('lux'),val('tareaLuz'));return box(r.exceeds?'bad':'ok',r.exceeds?'Por debajo del mínimo':'Alcanza el mínimo',`${fmt(r.value,0)} lux`,`Mínimo: ${r.limit} lux. Déficit: ${r.deficit} lux.<br>La comparación puntual no comprueba homogeneidad, distribución ni ausencia de deslumbramiento.`,'Numerales 30–31.');});
$('checks').innerHTML=[
['Postura del n. 38 >2 h/día: manos sobre cabeza, codos sobre hombros, cuello/tronco >30°, cuclillas o rodillas.','38'],
['Mismo movimiento de cuello, hombros, codos, muñecas o manos >4 veces/min durante >2 h/día.','38'],
['Esfuerzo de mano/muñeca >2 h/día: pinza con >1 kg, agarre de fuerza con desviación o atornillado intenso.','38'],
['Manos o rodillas como martillo >10 veces/h durante >2 h/día.','38'],
['Ingreso de datos en computadora >5 h efectivas al día.','16'],
['No hay pausa mínima de 10 min por cada 50 min de trabajo en ingreso de datos.','16']
].map(([t,n])=>`<label class="check"><input type="checkbox" data-label="${t}" data-n="${n}">${t}</label>`).join('');
window.presetTamizaje=()=>{clearChecks();const c=$('checks').querySelectorAll('input');c[1].checked=c[4].checked=c[5].checked=true;calcTamizaje()};
window.calcTamizaje=()=>result('resTamizaje',()=>{const selected=[...$('checks').querySelectorAll('input:checked')];return box(selected.length?'warn':'warn',selected.length?'Hallazgos para intervenir o evaluar':'Sin criterios marcados',`${selected.length} hallazgos`,selected.map(x=>`${esc(x.dataset.label)} (n. ${x.dataset.n})`).join('<br><br>')+'<p>El recuento no es una escala de gravedad. No equivale a RULA, REBA ni certifica ausencia de riesgo. Para el caso D no se asume un ángulo cervical >30° si no se ha medido.</p>','Numerales 16 y 38–40. Tamizaje parcial, no exhaustivo.');});

const stages=[['0–5','Activar','¿El problema de una caja de 18 kg es solo el peso? Una hipótesis por equipo.'],['5–12','Organizar','Equipos de hasta 3: observación, cálculo y registro. Compartir fotografía y control de tiempo.'],['12–32','Rally','Cuatro rondas de 4 min + 1 min de traslado. Revisar pantalla/asiento, ruta de carga, postura y ambiente.'],['32–38','Leer el caso','Asignar A–D. Identificar datos, unidades y qué falta saber.'],['38–60','Calcular','Ingresar valores, comparar límites y verificar con otro equipo. No adivinar datos.'],['60–72','Proponer controles','Una medida de diseño, una organizativa y una de apoyo. Añadir cómo comprobar su efecto.'],['72–84','Comunicar','Fotografiar la ficha. Presentar: observamos, calculamos, norma, decisión y controles.'],['84–90','Cerrar','Contrastar resultados. Explicar qué dato cambió la decisión. La infografía se completa después.']];
addPanel('practica','Práctica · 90 min',`<div class="card"><div class="work-head"><div><h2>Rally ErgoDetectives</h2><p class="lead">De la observación a una decisión sustentada.</p></div><span class="badge">90 minutos · Equipos de hasta 3</span></div><p>Celular, hojas A4 y lapicero. Sin pizarra. Caminen sin correr; no carguen peso real ni mantengan posturas dolorosas. Quien no pueda desplazarse participa como analista desde su asiento.</p><div class="timeline">${stages.map(([t,h,b])=>`<article class="step"><b>${t} min</b><strong>${h}</strong>${b}</article>`).join('')}</div><h3>Casos de trabajo</h3><div class="actions"><button class="btn" onclick="openPanel('carga');presetCarga()">A · Almacén</button><button class="btn" onclick="openPanel('ruido');presetRuido()">B · Ruido</button><button class="btn" onclick="openPanel('termico');presetWBGT()">C · Calor</button><button class="btn" onclick="openPanel('luz');presetLuz()">D · Cómputo</button></div><p>En D, completar también el tamizaje. Los casos son ficticios; los valores son didácticos, no mediciones del aula.</p><details><summary>Instrucciones de las cuatro estaciones</summary><ol><li><strong>Pantalla y asiento:</strong> observar pies, respaldo, alcance y altura de pantalla. N. 16, 17, 21.</li><li><strong>Ruta de carga:</strong> caminar sin objetos e identificar obstáculos y distancia. N. 9–12.</li><li><strong>Postura:</strong> describir una postura vista; no forzar una demostración. Distinguir observación, ángulo y duración. N. 38.</li><li><strong>Ambiente:</strong> localizar sombras/reflejos, fuentes de ruido y calor. El celular no sustituye instrumentos calibrados. N. 23–31.</li></ol></details><details><summary>Clave docente y evaluación</summary><p>A: 18 kg supera 15 kg; caja 70 × 65 cm requiere reducción y favorecer ayuda mecánica. B: 193,75 % de dosis. C: 28,8 °C frente a 28,5 °C. D: 360 lux frente a 500 lux; revisar digitación y pausas.</p><p>20 puntos: datos 4, cálculo/categoría 6, sustento 4, controles 4, comunicación 2. Estas claves son visibles; no usar como examen cerrado.</p></details></div>`);

addPanel('extras','Extras de la norma',`<div class="work-head"><h2>Calculadoras complementarias</h2><span class="badge">Criterios específicos · No certificación</span></div><p class="lead">Herramientas adicionales a los cuatro casos de la sesión.</p><div class="tool-cards">
<article class="card"><h3>Empuje y tracción</h3><p>Fuerza medida con dinamómetro, no masa del carro. Terreno plano y llantas adecuadas.</p><div class="fields">${field('force','Fuerza medida',18,'min="0"')}${select('forceUnit','Unidad',[['kgf','kgf'],['N','N']])}${select('forcePerson','Tabla',[['hombre','Hombres'],['mujer','Mujeres']])}${select('forcePhase','Fase',[['inicio','Sacar del reposo o detener'],['marcha','Mantener el movimiento']])}</div><button class="btn" onclick="extraForce()">Comparar fuerza</button><div class="result" id="forceResult" aria-live="polite">Pendiente de cálculo.</div></article>
<article class="card"><h3>Vibración</h3><p>Ingresar aceleración equivalente evaluada en una dirección. No mezclar aceleración pico, RMS y A(8).</p><div class="fields">${select('vMode','Tipo',[['mano','Mano-brazo'],['cuerpo','Cuerpo entero: solo 8 h']])}${field('vAcc','Aceleración equivalente (m/s²)',5,'min="0"')}${field('vHours','Exposición (h/día)',4,'min="0.001" max="24"')}</div><button class="btn" onclick="extraVibration()">Comparar vibración</button><div class="result" id="vResult" aria-live="polite">Pendiente de cálculo.</div></article>
<article class="card"><h3>Humedad relativa</h3><p>Aplicable a lugares con aire acondicionado.</p>${field('humidity','Humedad relativa (%)',35,'min="0" max="100"')}<button class="btn" onclick="extraHumidity()">Comparar humedad</button><div class="result" id="hResult" aria-live="polite">Pendiente de cálculo.</div></article>
<article class="card"><h3>Velocidad del aire</h3><p>Comparación descriptiva con los valores del n. 28; la norma no define aquí tolerancias.</p>${select('airTask','Ambiente y trabajo',[['0.25','No caluroso'],['0.5','Caluroso, sedentario'],['0.75','Caluroso, no sedentario']])}${field('airValue','Velocidad medida (m/s)',.2,'min="0"')}<button class="btn" onclick="extraAir()">Comparar referencia</button><div class="result" id="aResult" aria-live="polite">Pendiente de cálculo.</div></article>
<article class="card"><h3>LPR · producto de factores NIOSH</h3><p>Solo opera la ecuación del n. 7. El docente debe aportar LC y factores determinados mediante el método NIOSH completo. No se deducen factores ni se clasifica riesgo automáticamente.</p><div class="fields">${field('lc','LC (kg) · ingresar constante','','min="0.001"')}${['HM','VM','DM','AM','FM','CM'].map(k=>field(k,k+' · factor 0–1','','min="0" max="1"')).join('')}</div><button class="btn" onclick="extraNiosh()">Calcular LPR</button><div class="result" id="nResult" aria-live="polite">No hay valores precargados.</div></article>
<article class="card"><h3>Organización de digitación</h3><p>Planificación didáctica en bloques de hasta 50 min, con 10 min de pausa entre bloques. No incluye otras tareas o refrigerio.</p>${field('typing','Digitación efectiva total (min)',300,'min="1" max="1440"')}<button class="btn" onclick="extraTyping()">Planificar bloques</button><div class="result" id="tResult" aria-live="polite">Pendiente de cálculo.</div></article></div>`);
window.extraForce=()=>result('forceResult',()=>{const r=E.traccion(val('force'),val('forceUnit'),val('forcePerson'),val('forcePhase'));return box(r.exceeds?'bad':'ok',r.exceeds?'Supera la referencia':'No supera la referencia',`${fmt(r.kgf,2)} kgf`,`Límite: ${r.limit} kgf (${fmt(r.limit*9.80665,2)} N).<br>Conversión: 1 kgf = 9,80665 N. La tabla expresa fuerza como “kg”; aquí se interpreta kgf para distinguirla de masa.`,'Numeral 8.');});
window.extraVibration=()=>result('vResult',()=>{const r=E.vibracion(val('vAcc'),val('vHours'),val('vMode'));return box(r.limit===null?'warn':r.exceeds?'bad':r.action?'warn':'ok',r.status,`${fmt(r.value,2)} m/s²`,(r.limit===null?'Sin clasificación.':`Referencia superior: ${r.limit} m/s².`)+(val('vMode')==='mano'?'<p>Bandas: <1 h: 12; 1–<2 h: 8; 2–<4 h: 6; 4–8 h: 4 m/s². En 1, 2 y 4 h se adopta la banda más protectora porque los intervalos impresos se solapan.</p>':'<p>Para 8 h: acción 0,5; límite 1,15 m/s². No se calcula una normalización A(8) con esta tabla.</p>'),'Numerales 32–33.');});
window.extraHumidity=()=>result('hResult',()=>{const r=E.humedad(val('humidity'));return box(r.exceeds?'bad':'ok',r.status,`${fmt(r.value)} %`,'Rango inclusivo: 40–90 %. No extrapolar este criterio a ambientes sin aire acondicionado.','Numeral 29.');});
window.extraAir=()=>result('aResult',()=>{const v=E.num(val('airValue'),0,50),ref=number('airTask');return box('warn',Math.abs(v-ref)<1e-9?'Coincide con la referencia':v<ref?'Por debajo de la referencia':'Por encima de la referencia',`${fmt(v,2)} m/s`,`Referencia seleccionada: ${fmt(ref,2)} m/s. Diferencia: ${fmt(v-ref,2)} m/s. No se presenta como una certificación ni como un máximo/mínimo no especificado.`,'Numeral 28.');});
window.extraNiosh=()=>result('nResult',()=>{const r=E.niosh(val('lc'),['HM','VM','DM','AM','FM','CM'].map(val));return box('warn',r.zero?'LPR nulo: revisar condiciones':'LPR calculado',`${fmt(r.value,2)} kg`,'LPR = LC × HM × VM × DM × AM × FM × CM. Verifica aplicabilidad, origen/destino y factores con el método completo. No se asignan categorías de índice de levantamiento no descritas en el anexo.','Numeral 7.');});
window.extraTyping=()=>result('tResult',()=>{const m=E.num(val('typing'),1,1440),blocks=Math.ceil(m/50),pauses=blocks-1;return box(m>300?'bad':'ok',m>300?'Supera las 5 h efectivas':'No supera las 5 h efectivas',`${blocks} bloques`,`${pauses} pausas intermedias de 10 min: ${pauses*10} min. Duración planificada: ${m+pauses*10} min. Último bloque: ${m-(blocks-1)*50} min.<br>La cuenta excluye una pausa al terminar definitivamente; si continúa el trabajo, debe programarse el descanso que corresponda.`,'Numeral 16. Planificación didáctica, no cómputo legal de jornada.');});

addPanel('ficha','Ficha e infografía',`<div class="card"><h2>Ficha del equipo</h2><p class="lead">Completen, impriman o fotografíen. Los textos permanecen solo mientras esta página está abierta; no se envían ni guardan en un servidor.</p><div class="practice-fields">${['Equipo y caso','Riesgo observado','Datos y unidades','Cálculo y resultado','Categoría y numeral','Tres controles y cómo verificarlos','Conclusión'].map((t,i)=>`<label>${t}<textarea id="f${i}" placeholder="Escribe aquí…"></textarea></label>`).join('')}</div><div class="actions"><button class="btn" onclick="makePrompt()">Preparar texto para ChatGPT</button><button class="btn secondary" onclick="window.print()">Imprimir ficha</button></div><label>Texto listo para copiar<textarea id="promptText" readonly></textarea></label><button class="btn secondary" onclick="copyPrompt()">Copiar texto</button><p id="copyState" aria-live="polite"></p><p>Fotografía sin rostros ni datos personales: hoja plana, luz uniforme, encuadre completo. Comprueben cifras y unidades antes de pedir la infografía. El envío a ChatGPT es manual.</p></div>`);
window.makePrompt=()=>{const titles=['Equipo y caso','Riesgo observado','Datos y unidades','Cálculo y resultado','Categoría y numeral','Controles','Conclusión'];$('promptText').value='Elabora una infografía vertical en español a partir de esta ficha y las fotos adjuntas. No inventes ni corrijas silenciosamente datos: señala lo ilegible o inconsistente. Conserva valores, unidades y numerales. Incluye riesgo, cálculo, categoría, tres controles priorizados y conclusión. Diferencia datos del caso de observaciones reales. Añade «Uso formativo; no sustituye evaluación profesional».\n\n'+titles.map((t,i)=>t+': '+(val('f'+i).trim()||'[pendiente]')).join('\n');};
window.copyPrompt=async()=>{if(!val('promptText'))makePrompt();try{await navigator.clipboard.writeText(val('promptText'));$('copyState').textContent='Texto copiado.'}catch{$('promptText').focus();$('promptText').select();$('copyState').textContent='Selecciona y copia el texto manualmente.'}};
// La impresión de respuestas escritas usa texto, sin el recorte propio de textarea.
window.addEventListener('beforeprint',()=>document.querySelectorAll('#ficha textarea').forEach(x=>{const p=document.createElement('p');p.className='print-answer';p.style.whiteSpace='pre-wrap';p.textContent=x.value||'[Sin completar]';x.after(p);x.style.display='none'}));
window.addEventListener('afterprint',()=>{document.querySelectorAll('.print-answer').forEach(x=>x.remove());document.querySelectorAll('#ficha textarea').forEach(x=>x.style.display='')});
document.querySelector('.footer-tools .mini').innerHTML='RM 375-2008-TR · Herramienta formativa<br>Desarrollado por Sergio Bravo con Astra';
document.querySelectorAll('input[type=number]').forEach(x=>x.required=true);
// Primera vista de trabajo: datos y resultado consistentes, sin pantalla de bienvenida.
presetCarga();
